const DATABASENAME = '@gameplay';

const COLLECTION_USER = `${DATABASENAME}:user`;
const COLLECTION_APPOINTMENT = `${DATABASENAME}:appointment`;

export {
    COLLECTION_APPOINTMENT,
    COLLECTION_USER
}